import { 
  Finding, 
  Scan, 
  TargetProfile, 
  IdentityGraphNode, 
  IdentityGraphEdge, 
  GitForensicFinding, 
  BaselineComparison, 
  DomainIntelligence, 
  ReportItem 
} from '../types';

export const mockTargetProfile: TargetProfile = {
  name: "Keshav Gehlot",
  aliases: ["keshav-dev", "kgehlot", "kesh"],
  emails: ["keshav.gehlot@gmail.com", "keshav@cybersec.internal", "dev.keshav@outlook.com"],
  domains: ["cybersec.internal", "infra.corp.local", "staging.cybersec.io"],
  githubHandles: ["Keshav-gehlot", "keshav-sec"],
  hostnames: ["KESHAV-LAPTOP", "PROD-DB-NODE1", "SEC-DEVBOX-01"],
  homeCoordinates: [26.2389, 73.0243], // Jodhpur, India
};

export const mockFindings: Finding[] = [
  {
    id: "OPSEC-00101",
    ruleId: "aws_access_key",
    title: "AWS Production Access Key Exposed",
    description: "Active AWS IAM access key discovered in source code configuration. Direct identity anchor correlation detected.",
    category: "credentials",
    severity: "CRITICAL",
    riskScore: 9.8,
    confidence: 0.96,
    dimensions: {
      baseSeverity: 9.5,
      identityConfidence: 0.96,
      exposure: 0.95,
      exploitability: 0.92,
      persistence: 0.94,
      context: 0.90,
    },
    sourceType: "git_patch",
    origin: "config/aws_client.py",
    context: "commit 8f3a91b2 (author: Keshav Gehlot)",
    lineNumber: 42,
    commitSha: "8f3a91b2c4e67f890123456789abcdef01234567",
    author: "Keshav Gehlot",
    authorEmail: "keshav.gehlot@gmail.com",
    date: "2026-08-14T10:15:30Z",
    detectedText: "AWS_ACCESS_KEY_ID = \"AKIAIOSFODNN7EXAMPLE\"",
    maskedText: "AKIA••••••••••••MPLE",
    revealedText: "AKIAIOSFODNN7EXAMPLE",
    mitreTechnique: "T1552.001",
    mitreName: "Unsecured Credentials: Credentials In Files",
    cwe: "CWE-798",
    cweName: "Use of Hard-coded Credentials",
    status: "OPEN",
    firstSeen: "2026-08-14T10:15:30Z",
    lastSeen: "2026-08-20T18:30:00Z",
    occurrences: 4,
    lifecycleStatus: "ACTIVE_IN_HEAD",
    identityCorrelation: {
      matchedString: "keshav.gehlot@gmail.com",
      type: "Direct Email Anchor",
      reason: "Committed by known target author with linked personal email and active HEAD presence.",
    },
    remediationSteps: [
      "Revoke the IAM access key immediately in AWS Identity and Access Management console.",
      "Check AWS CloudTrail logs for unauthorized API calls executed using AKIAIOSFODNN7EXAMPLE.",
      "Remove the hardcoded credential from config/aws_client.py and utilize AWS Secrets Manager or environment variables.",
      "Rewrite Git repository history using git-filter-repo to purge historical blob references.",
      "Configure pre-commit scanning hooks to block future credential commits.",
    ],
    remediationCommands: [
      "aws iam update-access-key --access-key-id AKIAIOSFODNN7EXAMPLE --status Inactive",
      "git filter-repo --invert-paths --path config/aws_client.py --force",
      "git push origin --force --all",
    ],
  },
  {
    id: "OPSEC-00102",
    ruleId: "db_connection_string",
    title: "PostgreSQL Production Connection String",
    description: "Database connection string with embedded administrative credentials. Removed in HEAD but persistent in Git commit history.",
    category: "credentials",
    severity: "CRITICAL",
    riskScore: 9.4,
    confidence: 0.92,
    dimensions: {
      baseSeverity: 9.0,
      identityConfidence: 0.90,
      exposure: 0.88,
      exploitability: 0.95,
      persistence: 0.98,
      context: 0.92,
    },
    sourceType: "git_patch",
    origin: "backend/database.py",
    context: "commit 3b4c5d6e (author: kgehlot)",
    lineNumber: 18,
    commitSha: "3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c",
    author: "kgehlot",
    authorEmail: "keshav@cybersec.internal",
    date: "2026-07-28T14:22:10Z",
    detectedText: "postgres://postgres:MasterP@ssw0rd2026!@prod-db.cybersec.internal:5432/core_banking",
    maskedText: "postgres://postgres:••••••••••••@prod-db.cybersec.internal:5432/core_banking",
    revealedText: "postgres://postgres:MasterP@ssw0rd2026!@prod-db.cybersec.internal:5432/core_banking",
    mitreTechnique: "T1552.001",
    mitreName: "Unsecured Credentials: Credentials In Files",
    cwe: "CWE-798",
    cweName: "Use of Hard-coded Credentials",
    status: "OPEN",
    firstSeen: "2026-07-28T14:22:10Z",
    lastSeen: "2026-08-10T09:12:00Z",
    occurrences: 6,
    lifecycleStatus: "HISTORICAL_LEAK",
    identityCorrelation: {
      matchedString: "cybersec.internal",
      type: "Domain & Internal Host Anchor",
      reason: "Host prod-db.cybersec.internal matches target organization internal infrastructure domain.",
    },
    remediationSteps: [
      "Rotate PostgreSQL administrative password immediately on prod-db.cybersec.internal.",
      "Verify firewall ACLs restrict port 5432 to strictly authorized application subnet CIDRs.",
      "Purge the historical commit 3b4c5d6e from Git history.",
    ],
    remediationCommands: [
      "git filter-repo --replace-text <(echo 'postgres:MasterP@ssw0rd2026!==>postgres:REDACTED_SECRET')",
      "git push origin --force --all",
    ],
  },
  {
    id: "OPSEC-00103",
    ruleId: "internal_hostname",
    title: "Internal Infrastructure Hostname Exposed",
    description: "Internal cluster node hostname referenced in staging deployment scripts and commit logs.",
    category: "infrastructure",
    severity: "HIGH",
    riskScore: 8.2,
    confidence: 0.88,
    dimensions: {
      baseSeverity: 7.5,
      identityConfidence: 0.88,
      exposure: 0.85,
      exploitability: 0.80,
      persistence: 0.90,
      context: 0.82,
    },
    sourceType: "git_file_path",
    origin: "infra/k8s/node-sec-devbox-01.yaml",
    context: "infra/k8s/node-sec-devbox-01.yaml:12",
    lineNumber: 12,
    commitSha: "7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f",
    author: "Keshav Gehlot",
    authorEmail: "keshav.gehlot@gmail.com",
    date: "2026-08-02T11:05:00Z",
    detectedText: "SEC-DEVBOX-01.infra.corp.local",
    maskedText: "SEC-DEVBOX-01.••••••••••••",
    revealedText: "SEC-DEVBOX-01.infra.corp.local",
    mitreTechnique: "T1592.001",
    mitreName: "Gather Victim Host Information: Hardware",
    cwe: "CWE-200",
    cweName: "Exposure of Sensitive Information to an Unauthorized Actor",
    status: "OPEN",
    firstSeen: "2026-08-02T11:05:00Z",
    lastSeen: "2026-08-18T16:45:00Z",
    occurrences: 3,
    lifecycleStatus: "ACTIVE_IN_HEAD",
    identityCorrelation: {
      matchedString: "SEC-DEVBOX-01",
      type: "Target Hostname Anchor",
      reason: "Direct match against developer machine hostname cataloged in target profile.",
    },
    remediationSteps: [
      "Replace specific hostnames with generic environment aliases or DNS service discovery names.",
      "Audit internal DNS zoning to ensure .corp.local is not queryable from external resolvers.",
    ],
  },
  {
    id: "OPSEC-00104",
    ruleId: "media_gps_exif",
    title: "GPS Geolocation Leak in Media Metadata",
    description: "High-precision latitude/longitude coordinates extracted from document EXIF data within 2.3km of known target anchor.",
    category: "metadata",
    severity: "HIGH",
    riskScore: 7.9,
    confidence: 0.94,
    dimensions: {
      baseSeverity: 7.0,
      identityConfidence: 0.94,
      exposure: 0.80,
      exploitability: 0.85,
      persistence: 0.90,
      context: 0.86,
    },
    sourceType: "media_exif",
    origin: "docs/architecture_whitepaper_diagram.png",
    context: "EXIF GPS Latitude: 26.2410 N, Longitude: 73.0295 E",
    detectedText: "26.241021, 73.029548",
    maskedText: "26.24•••, 73.02••• (Jodhpur Vicinity)",
    revealedText: "26.241021, 73.029548",
    mitreTechnique: "T1589.001",
    mitreName: "Gather Victim Identity Information: Credentials/Location",
    cwe: "CWE-312",
    cweName: "Cleartext Storage of Sensitive Information",
    status: "IN_REVIEW",
    firstSeen: "2026-08-05T08:30:00Z",
    lastSeen: "2026-08-20T12:00:00Z",
    occurrences: 1,
    identityCorrelation: {
      matchedString: "26.2389, 73.0243",
      type: "GPS Proximity Match",
      reason: "Coordinates are within 2.34 km of target profile home location coordinate.",
    },
    remediationSteps: [
      "Strip EXIF and GPS metadata using exiftool or Pillow pipeline before publishing public documents.",
      "Enforce media sanitization in CI/CD publishing workflows.",
    ],
    remediationCommands: [
      "exiftool -all= docs/architecture_whitepaper_diagram.png",
    ],
  },
  {
    id: "OPSEC-00105",
    ruleId: "gcp_service_account_key",
    title: "GCP Service Account JSON Key",
    description: "Private service account key file containing RSA private key for cloud storage ingestion pipeline.",
    category: "credentials",
    severity: "HIGH",
    riskScore: 8.7,
    confidence: 0.95,
    dimensions: {
      baseSeverity: 9.0,
      identityConfidence: 0.88,
      exposure: 0.85,
      exploitability: 0.90,
      persistence: 0.92,
      context: 0.90,
    },
    sourceType: "git_patch",
    origin: "scripts/gcp_sa_key.json",
    context: "commit 1a2b3c4d (author: Keshav-gehlot)",
    lineNumber: 5,
    commitSha: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    author: "Keshav-gehlot",
    authorEmail: "dev.keshav@outlook.com",
    date: "2026-08-11T19:40:00Z",
    detectedText: "\"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQE...\"",
    maskedText: "\"private_key\": \"-----BEGIN PRIVATE KEY-----\\n••••••••••••\"",
    revealedText: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC...\n-----END PRIVATE KEY-----",
    mitreTechnique: "T1552.004",
    mitreName: "Unsecured Credentials: Private Keys",
    cwe: "CWE-798",
    cweName: "Use of Hard-coded Credentials",
    status: "OPEN",
    firstSeen: "2026-08-11T19:40:00Z",
    lastSeen: "2026-08-20T18:00:00Z",
    occurrences: 2,
    lifecycleStatus: "ACTIVE_IN_HEAD",
    identityCorrelation: {
      matchedString: "Keshav-gehlot",
      type: "GitHub Handle Anchor",
      reason: "Author handle corresponds to verified target GitHub developer profile.",
    },
    remediationSteps: [
      "Delete and rotate the GCP Service Account Key in Google Cloud IAM.",
      "Switch workload authentication to Workload Identity Federation instead of static JSON keys.",
      "Remove key file and scrub history.",
    ],
    remediationCommands: [
      "gcloud iam service-accounts keys delete <KEY_ID> --iam-account=scanner-ingest@project.iam.gserviceaccount.com",
    ],
  },
  {
    id: "OPSEC-00106",
    ruleId: "vpn_endpoint_disclosure",
    title: "Internal VPN Gateway Configuration",
    description: "WireGuard / OpenVPN endpoint address and pre-shared tunnel credentials disclosed in test fixtures.",
    category: "infrastructure",
    severity: "HIGH",
    riskScore: 7.8,
    confidence: 0.85,
    dimensions: {
      baseSeverity: 7.5,
      identityConfidence: 0.82,
      exposure: 0.80,
      exploitability: 0.88,
      persistence: 0.85,
      context: 0.84,
    },
    sourceType: "git_patch",
    origin: "tests/fixtures/vpn_config.ovpn",
    context: "tests/fixtures/vpn_config.ovpn:4",
    lineNumber: 4,
    commitSha: "9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a",
    author: "kgehlot",
    authorEmail: "keshav@cybersec.internal",
    date: "2026-08-16T15:10:00Z",
    detectedText: "remote vpn.cybersec.internal 1194",
    maskedText: "remote vpn.•••••••••••• 1194",
    revealedText: "remote vpn.cybersec.internal 1194",
    mitreTechnique: "T1133",
    mitreName: "External Remote Services",
    cwe: "CWE-200",
    cweName: "Exposure of Sensitive Information",
    status: "OPEN",
    firstSeen: "2026-08-16T15:10:00Z",
    lastSeen: "2026-08-20T18:00:00Z",
    occurrences: 2,
    lifecycleStatus: "ACTIVE_IN_HEAD",
    identityCorrelation: {
      matchedString: "cybersec.internal",
      type: "Domain Match",
      reason: "Domain associated with target's internal infrastructure network.",
    },
    remediationSteps: [
      "Mask live VPN endpoint hostnames with mock dummy hosts in test fixtures.",
      "Regenerate VPN pre-shared keys and client certificates.",
    ],
  },
  {
    id: "OPSEC-00107",
    ruleId: "author_email_exposure",
    title: "Personal Email Identity in Corporate Commits",
    description: "Personal Gmail address used across multiple corporate repository commits, establishing developer cross-correlation.",
    category: "identity",
    severity: "MEDIUM",
    riskScore: 5.6,
    confidence: 0.98,
    dimensions: {
      baseSeverity: 5.0,
      identityConfidence: 0.98,
      exposure: 0.75,
      exploitability: 0.60,
      persistence: 0.95,
      context: 0.70,
    },
    sourceType: "git_commit_meta",
    origin: "Git Author Signature",
    context: "18 commits in branch main",
    author: "Keshav Gehlot",
    authorEmail: "keshav.gehlot@gmail.com",
    date: "2026-08-19T14:00:00Z",
    detectedText: "Keshav Gehlot <keshav.gehlot@gmail.com>",
    maskedText: "Keshav Gehlot <keshav.•••••@gmail.com>",
    revealedText: "Keshav Gehlot <keshav.gehlot@gmail.com>",
    mitreTechnique: "T1589.002",
    mitreName: "Gather Victim Identity Information: Email Addresses",
    cwe: "CWE-200",
    cweName: "Exposure of Sensitive Information",
    status: "OPEN",
    firstSeen: "2026-07-15T09:00:00Z",
    lastSeen: "2026-08-20T20:30:00Z",
    occurrences: 18,
    lifecycleStatus: "ACTIVE_IN_HEAD",
    identityCorrelation: {
      matchedString: "keshav.gehlot@gmail.com",
      type: "Direct Identity Anchor",
      reason: "Exact match with primary personal email registered in target profile.",
    },
    remediationSteps: [
      "Configure git author email per repository: git config user.email dev@corporate.com",
      "Use GitHub commit email privacy features (noreply address).",
    ],
    remediationCommands: [
      "git config user.email keshav@cybersec.internal",
    ],
  },
  {
    id: "OPSEC-00108",
    ruleId: "staging_subdomain_leak",
    title: "Staging Cluster Subdomain Disclosed",
    description: "Pre-production Kubernetes staging ingress endpoint exposed in documentation URLs.",
    category: "infrastructure",
    severity: "MEDIUM",
    riskScore: 6.2,
    confidence: 0.89,
    dimensions: {
      baseSeverity: 6.0,
      identityConfidence: 0.85,
      exposure: 0.80,
      exploitability: 0.70,
      persistence: 0.85,
      context: 0.78,
    },
    sourceType: "git_patch",
    origin: "README.md",
    context: "README.md:88",
    lineNumber: 88,
    detectedText: "https://staging.cybersec.io/api/v1/metrics",
    maskedText: "https://staging.••••••••••••/api/v1/metrics",
    revealedText: "https://staging.cybersec.io/api/v1/metrics",
    mitreTechnique: "T1592",
    mitreName: "Gather Victim Host Information",
    cwe: "CWE-200",
    cweName: "Exposure of Sensitive Information",
    status: "RESOLVED",
    firstSeen: "2026-08-01T12:00:00Z",
    lastSeen: "2026-08-15T10:00:00Z",
    occurrences: 1,
    identityCorrelation: {
      matchedString: "staging.cybersec.io",
      type: "Target Domain Match",
      reason: "Matches registered staging domain in profile.",
    },
    remediationSteps: [
      "Restrict staging API endpoints behind mTLS or Cloudflare Zero Trust Access.",
      "Remove direct staging URLs from public markdown documentation.",
    ],
  },
];

export const mockScans: Scan[] = [
  {
    id: "scan-2026-0820-01",
    target: "Keshav-gehlot/OPSEC_leak_scanner",
    targetType: "git",
    status: "completed",
    progress: 100,
    scanDepth: "forensic",
    startedAt: "2026-08-20T20:45:00Z",
    completedAt: "2026-08-20T20:45:38Z",
    stats: {
      filesScanned: 1248,
      commitsAnalyzed: 482,
      rulesEvaluated: 96,
      findingsDiscovered: 18,
      criticalCount: 2,
      highCount: 5,
      mediumCount: 7,
      lowCount: 4,
    },
    riskScore: 7.8,
  },
  {
    id: "scan-2026-0819-02",
    target: "e:/opsec-scanner/media_archive",
    targetType: "media",
    status: "completed",
    progress: 100,
    scanDepth: "full_history",
    startedAt: "2026-08-19T14:10:00Z",
    completedAt: "2026-08-19T14:12:15Z",
    stats: {
      filesScanned: 340,
      commitsAnalyzed: 0,
      rulesEvaluated: 84,
      findingsDiscovered: 6,
      criticalCount: 0,
      highCount: 2,
      mediumCount: 3,
      lowCount: 1,
    },
    riskScore: 5.4,
  },
];

export const mockIdentityGraphNodes: IdentityGraphNode[] = [
  {
    id: "node-target",
    type: "target",
    label: "Keshav Gehlot",
    sublabel: "Target Anchor",
    category: "identity",
    confidence: 1.0,
    details: { "Role": "Primary Target", "Identity Anchors": 8, "Confidence": "100%" },
    x: 400,
    y: 50,
  },
  {
    id: "node-email-personal",
    type: "email",
    label: "keshav.gehlot@gmail.com",
    sublabel: "Personal Email",
    category: "identity",
    confidence: 0.98,
    details: { "Type": "Personal Email", "Commits Authored": 18, "First Seen": "2026-07-15" },
    x: 180,
    y: 180,
  },
  {
    id: "node-email-corp",
    type: "email",
    label: "keshav@cybersec.internal",
    sublabel: "Corporate Email",
    category: "identity",
    confidence: 0.95,
    details: { "Type": "Internal Domain", "Commits Authored": 34, "Domain": "cybersec.internal" },
    x: 400,
    y: 180,
  },
  {
    id: "node-github",
    type: "github",
    label: "Keshav-gehlot",
    sublabel: "GitHub Account",
    category: "identity",
    confidence: 0.99,
    details: { "Platform": "GitHub", "Repos": 12, "Profile Verified": "Yes" },
    x: 620,
    y: 180,
  },
  {
    id: "node-hostname",
    type: "hostname",
    label: "SEC-DEVBOX-01",
    sublabel: "Dev Workstation",
    category: "infrastructure",
    confidence: 0.88,
    details: { "OS": "Linux / Dev Workstation", "Domain": "infra.corp.local", "Leaks": 2 },
    x: 820,
    y: 280,
  },
  {
    id: "node-repo",
    type: "repo",
    label: "OPSEC_leak_scanner",
    sublabel: "Git Repository",
    category: "git",
    confidence: 1.0,
    details: { "Branches": 4, "Commits": 482, "Visibility": "Public" },
    x: 400,
    y: 320,
  },
  {
    id: "node-commit-1",
    type: "commit",
    label: "Commit 8f3a91b2",
    sublabel: "AWS Key Intro",
    category: "git",
    confidence: 0.96,
    details: { "Author": "Keshav Gehlot", "Date": "2026-08-14", "Status": "Active in HEAD" },
    x: 200,
    y: 450,
  },
  {
    id: "node-secret-aws",
    type: "secret",
    label: "AKIA••••••••MPLE",
    sublabel: "AWS IAM Key",
    category: "secrets",
    confidence: 0.96,
    details: { "Severity": "CRITICAL", "Risk": 9.8, "Service": "Amazon Web Services" },
    x: 200,
    y: 580,
  },
  {
    id: "node-commit-2",
    type: "commit",
    label: "Commit 3b4c5d6e",
    sublabel: "DB Conn Intro",
    category: "git",
    confidence: 0.94,
    details: { "Author": "kgehlot", "Date": "2026-07-28", "Status": "Historical Leak" },
    x: 580,
    y: 450,
  },
  {
    id: "node-secret-db",
    type: "secret",
    label: "postgres://postgres:•••",
    sublabel: "PostgreSQL DB Key",
    category: "secrets",
    confidence: 0.94,
    details: { "Severity": "CRITICAL", "Risk": 9.4, "Database": "PostgreSQL 16" },
    x: 580,
    y: 580,
  },
  {
    id: "node-gps",
    type: "gps",
    label: "26.2410 N, 73.0295 E",
    sublabel: "Jodhpur Proximity",
    category: "metadata",
    confidence: 0.94,
    details: { "Distance to Home": "2.34 km", "Source": "architecture_diagram.png" },
    x: 50,
    y: 320,
  },
  {
    id: "node-domain",
    type: "domain",
    label: "cybersec.internal",
    sublabel: "Internal Infra",
    category: "infrastructure",
    confidence: 0.92,
    details: { "Classification": "INTERNAL", "Services": "Database, VPN, API" },
    x: 820,
    y: 450,
  },
];

export const mockIdentityGraphEdges: IdentityGraphEdge[] = [
  { id: "e1", source: "node-target", target: "node-email-personal", label: "CO_OCCURS_WITH" },
  { id: "e2", source: "node-target", target: "node-email-corp", label: "RESOLVES_TO" },
  { id: "e3", source: "node-target", target: "node-github", label: "RESOLVES_TO" },
  { id: "e4", source: "node-github", target: "node-repo", label: "AUTHORED" },
  { id: "e5", source: "node-email-corp", target: "node-repo", label: "COMMITTED_BY" },
  { id: "e6", source: "node-repo", target: "node-commit-1", label: "CONTAINS" },
  { id: "e7", source: "node-repo", target: "node-commit-2", label: "CONTAINS" },
  { id: "e8", source: "node-commit-1", target: "node-secret-aws", label: "CONTAINS", animated: true },
  { id: "e9", source: "node-commit-2", target: "node-secret-db", label: "CONTAINS", animated: true },
  { id: "e10", source: "node-target", target: "node-hostname", label: "RUNS_ON" },
  { id: "e11", source: "node-target", target: "node-gps", label: "GEO_PROXIMATE" },
  { id: "e12", source: "node-email-corp", target: "node-domain", label: "RESOLVES_TO" },
  { id: "e13", source: "node-hostname", target: "node-domain", label: "RESOLVES_TO" },
];

export const mockGitForensicFindings: GitForensicFinding[] = [
  {
    findingId: "OPSEC-00102",
    title: "PostgreSQL Database Credentials Lifecycle",
    secretType: "Database Connection String",
    currentStatus: "HISTORICAL_LEAK",
    firstSeenDate: "2026-07-28T14:22:10Z",
    lastSeenDate: "2026-08-10T09:12:00Z",
    commitsPersistent: 6,
    firstAuthor: "kgehlot (keshav@cybersec.internal)",
    lastAuthor: "Keshav Gehlot (keshav.gehlot@gmail.com)",
    safeRemediationCommand: "git filter-repo --replace-text <(echo 'postgres:MasterP@ssw0rd2026!==>postgres:REDACTED')",
    timeline: [
      {
        sha: "3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c",
        shortSha: "3b4c5d6e",
        author: "kgehlot",
        authorEmail: "keshav@cybersec.internal",
        date: "2026-07-28 14:22:10",
        message: "feat: initialize postgresql connection pool",
        action: "introduced",
        branch: "feature/db-connector",
        file: "backend/database.py",
        line: 18,
        patchSnippet: "+ DB_URI = 'postgres://postgres:MasterP@ssw0rd2026!@prod-db.cybersec.internal:5432/core_banking'",
      },
      {
        sha: "5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b",
        shortSha: "5a6b7c8d",
        author: "kgehlot",
        authorEmail: "keshav@cybersec.internal",
        date: "2026-08-01 11:15:00",
        message: "refactor: add connection retry logic",
        action: "modified",
        branch: "main",
        file: "backend/database.py",
        line: 22,
        patchSnippet: "  DB_URI = 'postgres://postgres:MasterP@ssw0rd2026!@prod-db.cybersec.internal:5432/core_banking'",
      },
      {
        sha: "9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d",
        shortSha: "9c0d1e2f",
        author: "Keshav Gehlot",
        authorEmail: "keshav.gehlot@gmail.com",
        date: "2026-08-10 09:12:00",
        message: "fix: remove hardcoded db credential string from source",
        action: "deleted_in_head",
        branch: "main",
        file: "backend/database.py",
        line: 22,
        patchSnippet: "- DB_URI = 'postgres://postgres:MasterP@ssw0rd2026!@prod-db.cybersec.internal:5432/core_banking'\n+ DB_URI = os.getenv('DATABASE_URL')",
      },
      {
        sha: "HEAD (commit c410a54)",
        shortSha: "HEAD",
        author: "Keshav Gehlot",
        authorEmail: "keshav.gehlot@gmail.com",
        date: "2026-08-20 20:30:00",
        message: "HEAD state: Removed from working tree but easily extracted via git cat-file / rev-list",
        action: "historical_persistence",
        branch: "main",
        file: "backend/database.py",
        line: 0,
        patchSnippet: "⚠ FORENSIC ALERT: Secret remains fully recoverable by analyzing commit 3b4c5d6e object tree.",
      },
    ],
  },
];

export const mockBaselineComparison: BaselineComparison = {
  baselineId: "baseline-v0.5.0",
  baselineDate: "2026-08-12T10:00:00Z",
  currentScanId: "scan-2026-0820-01",
  newCount: 2,
  resolvedCount: 3,
  unchangedCount: 11,
  diffs: [
    {
      finding: mockFindings[0], // AWS Key
      diffStatus: "NEW",
    },
    {
      finding: mockFindings[4], // GCP SA Key
      diffStatus: "NEW",
    },
    {
      finding: mockFindings[7], // Staging leak
      diffStatus: "RESOLVED",
    },
    {
      finding: mockFindings[1], // DB String
      diffStatus: "UNCHANGED",
    },
    {
      finding: mockFindings[2], // Hostname
      diffStatus: "UNCHANGED",
    },
    {
      finding: mockFindings[3], // GPS
      diffStatus: "UNCHANGED",
    },
    {
      finding: mockFindings[5], // VPN
      diffStatus: "UNCHANGED",
    },
    {
      finding: mockFindings[6], // Email
      diffStatus: "UNCHANGED",
    },
  ],
};

export const mockDomainIntelligence: DomainIntelligence[] = [
  {
    id: "dom-1",
    domain: "cybersec.internal",
    classification: "INTERNAL",
    severity: "CRITICAL",
    riskReason: "Internal corporate TLD used for database clustering and service discovery.",
    associatedFindings: 4,
    environment: "Core Production Infrastructure",
    firstDiscovered: "2026-07-20",
    ipAddresses: ["10.240.0.12", "10.240.0.15"],
  },
  {
    id: "dom-2",
    domain: "vpn.cybersec.internal",
    classification: "VPN",
    severity: "HIGH",
    riskReason: "Remote access gateway gateway hostname with disclosed port mappings.",
    associatedFindings: 2,
    environment: "Network Perimeter / Ingress",
    firstDiscovered: "2026-08-16",
    ipAddresses: ["192.168.100.1"],
  },
  {
    id: "dom-3",
    domain: "grafana.cybersec.internal",
    classification: "MONITORING",
    severity: "HIGH",
    riskReason: "Internal observability dashboard exposing telemetry metrics.",
    associatedFindings: 1,
    environment: "Observability / Telemetry",
    firstDiscovered: "2026-08-04",
    ipAddresses: ["10.240.4.88"],
  },
  {
    id: "dom-4",
    domain: "staging.cybersec.io",
    classification: "STAGING",
    severity: "MEDIUM",
    riskReason: "Pre-production cloud staging cluster exposed in public docs.",
    associatedFindings: 1,
    environment: "Cloud Staging Cluster",
    firstDiscovered: "2026-08-01",
    ipAddresses: ["34.120.45.92"],
  },
  {
    id: "dom-5",
    domain: "infra.corp.local",
    classification: "INTERNAL",
    severity: "MEDIUM",
    riskReason: "Internal mDNS / Active Directory domain suffix.",
    associatedFindings: 2,
    environment: "Office LAN / Active Directory",
    firstDiscovered: "2026-08-02",
  },
  {
    id: "dom-6",
    domain: "github.com",
    classification: "PUBLIC",
    severity: "LOW",
    riskReason: "Public source hosting platform repository references.",
    associatedFindings: 18,
    environment: "Public Web",
    firstDiscovered: "2026-07-15",
  },
];

export const mockReports: ReportItem[] = [
  {
    id: "rep-1",
    title: "Interactive SOC HTML Audit Dossier",
    format: "HTML",
    generatedAt: "2026-08-20 20:55:38",
    size: "44.5 KB",
    description: "Self-contained interactive case file with click-to-reveal secret disclosure.",
    downloadFilename: "opsec_report.html",
  },
  {
    id: "rep-2",
    title: "Executive PDF Security Briefing",
    format: "PDF",
    generatedAt: "2026-08-20 20:55:40",
    size: "22.1 KB",
    description: "Formal PDF export with redacted credential markers and risk breakdowns.",
    downloadFilename: "opsec_report.pdf",
  },
  {
    id: "rep-3",
    title: "Raw Findings JSON Data Stream",
    format: "JSON",
    generatedAt: "2026-08-20 20:55:39",
    size: "20.6 KB",
    description: "Machine-readable JSON schema with confidence multipliers and provenance.",
    downloadFilename: "opsec_report.json",
  },
  {
    id: "rep-4",
    title: "SARIF 2.1.0 Static Analysis Interchange",
    format: "SARIF",
    generatedAt: "2026-08-20 20:55:39",
    size: "20.5 KB",
    description: "OASIS Standard SARIF for GitHub Code Scanning and GitLab Security pipelines.",
    downloadFilename: "opsec_report.sarif",
  },
];
